# Generated by Django 4.1.5 on 2023-01-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('numero_de_maquinas', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('estado', models.CharField(blank=True, choices=[('DIPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(blank=True, choices=[('AGRONEGOCIOS', 'Agronegocios'), ('ADMINISTRACION DE EMPRESAS', 'Administracion de Empresas'), ('NEGOCIOS INTERNACIONALES', 'Negocios Internacionales'), ('MARKETING', 'Marketing'), ('ARQUITECTURA', 'Arquitectura'), ('DERECHO', 'Derecho'), ('TECNOLOGIAS DE LA INFORMACION Y COMUNICACION', 'Tecnologias de la Informacion y Comunicacion'), ('TURISMO', 'Turismo'), ('PSICOLOGIA', 'Psicologia')], max_length=50, null=True)),
                ('duracion', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_de_maquinas', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('DIPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_identidad', models.CharField(blank=True, choices=[('CEDULA', 'Cedula'), ('PASAPORTE', 'Pasaporte')], max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salasdelectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_de_maquinas', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('estado', models.CharField(blank=True, choices=[('DIPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('foto_docente', models.ImageField(blank=True, null=True, upload_to='static/fotos_docente')),
                ('carrera', models.ManyToManyField(blank=True, to='api.carrera')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('foto_estudiante', models.ImageField(blank=True, null=True, upload_to='static/fotos_estudiante')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.biblioteca')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio')),
                ('salasdelectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salasdelectura')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docente'),
        ),
        migrations.AddField(
            model_name='materia',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to='api.estudiante'),
        ),
    ]
