# Generated by Django 4.1.5 on 2023-01-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.biblioteca'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='salasdelectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salasdelectura'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.biblioteca'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='salasdelectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salasdelectura'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.carrera'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.docente'),
        ),
    ]
