# Generated by Django 4.1.5 on 2023-01-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reserva_biblioteca_reserva_salasdelectura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.biblioteca')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_salasdelectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
                ('salasdelectura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salasdelectura')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
