# Generated by Django 4.1.5 on 2023-01-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reserva_biblioteca_reserva_laboratorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_biblioteca',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reserva_laboratorio',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reserva_salasdelectura',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='salasdelectura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='salasdelectura',
            name='numero_de_maquinas',
        ),
        migrations.AddField(
            model_name='reserva_biblioteca',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.docente'),
        ),
        migrations.AddField(
            model_name='reserva_biblioteca',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estudiante'),
        ),
        migrations.AddField(
            model_name='reserva_biblioteca',
            name='numero_maquina',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva_laboratorio',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.docente'),
        ),
        migrations.AddField(
            model_name='reserva_laboratorio',
            name='estudiante',
            field=models.ManyToManyField(blank=True, null=True, to='api.estudiante'),
        ),
        migrations.AddField(
            model_name='reserva_salasdelectura',
            name='docente',
            field=models.ManyToManyField(blank=True, null=True, to='api.docente'),
        ),
        migrations.AddField(
            model_name='reserva_salasdelectura',
            name='estudiante',
            field=models.ManyToManyField(blank=True, null=True, to='api.estudiante'),
        ),
    ]
