# Generated by Django 4.1.5 on 2023-01-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reserva_biblioteca_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_laboratorio',
            name='docente',
        ),
        migrations.AddField(
            model_name='reserva_laboratorio',
            name='docente',
            field=models.ManyToManyField(blank=True, null=True, to='api.docente'),
        ),
    ]
